// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMEAppHouse.Ladon.Infrastructure.Persistence;

#nullable disable

namespace SMEAppHouse.Ladon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240531072127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d536ae67-d35d-42d3-a87a-ee85eb95664d"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("58c1e699-845b-40c4-a7d8-cae039dd4743"),
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("491af811-3c00-4907-aa04-f66d29e08f38"),
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = new Guid("7661d4b7-5022-4ad5-aee5-f34cc78fd680"),
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = new Guid("4d921678-b584-4065-8b87-2ad098281fe3"),
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = new Guid("0a0e63b9-a559-4041-bd3c-828603cd6dc3"),
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c4d2914-5bfe-49f5-b81c-94a3e6789d1f"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b163a02-6a2c-4df2-bbb4-16ad7f80f4a8",
                            Email = "jc.mangubat@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JC.MANGUBAT@HOTMAIL.COM",
                            NormalizedUserName = "JC.MANGUBAT@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJH3o9lo9zm4swR2xWk/lWILwjXB/KLhd3IHagT5dqwiEKvm7KN3ciCXcrEmxIKzhg==",
                            PhoneNumber = "+639672814641",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47cf6a00-178a-d92a-b9e3-79bd1ff391c8_20240531072126224",
                            TwoFactorEnabled = false,
                            UserName = "jc.mangubat@hotmail.com"
                        },
                        new
                        {
                            Id = new Guid("c604f261-fd9d-4881-b640-47dbe5569295"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c93505e-1e3e-4963-8cfc-fad9d8463615",
                            Email = "ladonconst@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LADONCONST@GMAIL.COM",
                            NormalizedUserName = "LADONCONST@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMrDaXn4sL3S/Hz6iDspf2whiboaTYsZhZsSafoZwLhaHjqsoLv0fDTuw+EAH5iRJg==",
                            PhoneNumber = "+639951225449",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47cf6a00-178a-d92a-b9e3-79bd1ff391c8_20240531072126224",
                            TwoFactorEnabled = false,
                            UserName = "ladonconst@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("3c4d2914-5bfe-49f5-b81c-94a3e6789d1f"),
                            RoleId = new Guid("d536ae67-d35d-42d3-a87a-ee85eb95664d")
                        },
                        new
                        {
                            UserId = new Guid("c604f261-fd9d-4881-b640-47dbe5569295"),
                            RoleId = new Guid("58c1e699-845b-40c4-a7d8-cae039dd4743")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("Name")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AddressId")
                        .HasColumnOrder(0);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AddressLine2");

                    b.Property<int>("AddressType")
                        .HasColumnType("int")
                        .HasColumnName("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 15, 21, 26, 218, DateTimeKind.Local).AddTicks(1790))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("Region")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Region");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Addresses", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9caec870-f9fe-4382-b629-e2e9e76d6097"),
                            AddressLine1 = "Lot20 Blk10 Park Villas 1",
                            AddressLine2 = "Ellenita Heights, Catalunan Grande",
                            AddressType = 2,
                            City = "Davao",
                            Country = "Philippines",
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4680),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4680),
                            IsActive = true,
                            PostalCode = "8000",
                            Region = "Davao del Sur",
                            UserProfileId = new Guid("298ec5a2-660f-4d29-82c6-8bb69b83c3b6")
                        },
                        new
                        {
                            Id = new Guid("77d90d86-4392-40d4-8e77-faadbc76218a"),
                            AddressLine1 = "",
                            AddressLine2 = "Tierra Nueva Tacunan, Tugbok",
                            AddressType = 2,
                            City = "Davao",
                            Country = "Philippines",
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4684),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4685),
                            IsActive = true,
                            PostalCode = "8000",
                            Region = "Davao del Sur",
                            UserProfileId = new Guid("89458483-cb6f-4db7-af2e-f108d05666f0")
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogCommentId")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("BlogDocumentId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogDocumentId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 15, 21, 26, 222, DateTimeKind.Local).AddTicks(8331))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("Email");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("BlogDocumentId");

                    b.ToTable("BlogComments", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogDocumentId")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthorName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AuthorName");

                    b.Property<Guid?>("AuthorUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuthorUserProfileId");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CanonicalUrl");

                    b.Property<string>("Categories")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Categories");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Content");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 15, 21, 26, 219, DateTimeKind.Local).AddTicks(1081))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<int?>("Hearts")
                        .HasColumnType("int")
                        .HasColumnName("Hearts");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("IsFeatured");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModified");

                    b.Property<int?>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("Likes");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MetaDescription");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MetaKeywords");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PublishDate");

                    b.Property<string>("Slug")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Slug");

                    b.Property<string>("Tags")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("Tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Title");

                    b.Property<int?>("Views")
                        .HasColumnType("int")
                        .HasColumnName("Views");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserProfileId");

                    b.ToTable("BlogDocuments", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogRelatedAssociation", b =>
                {
                    b.Property<Guid>("SourceBlogDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetBlogDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SourceBlogDocumentId", "TargetBlogDocumentId");

                    b.HasIndex("TargetBlogDocumentId");

                    b.ToTable("BlogRelatedAssociation", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.ClientTestimony", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClientTestimonyId")
                        .HasColumnOrder(0);

                    b.Property<string>("ClientBusinessName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ClientBusinessName");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ClientName");

                    b.Property<string>("ClientProfession")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ClientProfession");

                    b.Property<string>("ClientThumnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ClientThumnailUrl");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 15, 21, 26, 218, DateTimeKind.Local).AddTicks(8640))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive")
                        .HasColumnOrder(506);

                    b.Property<string>("ProjectImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProjectImageUrl");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Remarks");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ClientTestimonies", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MessageId")
                        .HasColumnOrder(0);

                    b.Property<string>("ContentHtml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentHtml");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 15, 21, 26, 217, DateTimeKind.Local).AddTicks(7360))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MobilePhoneNo");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("SiteMessageSource")
                        .HasColumnType("int")
                        .HasColumnName("SiteMessageSource");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Subject");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Messages", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestId")
                        .HasColumnOrder(0);

                    b.Property<string>("AdditionalCommentsOrQuestions")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("AdditionalCommentsOrQuestions");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AddressLine2");

                    b.Property<decimal?>("BudgetMaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetMaxAmount");

                    b.Property<decimal?>("BudgetMinAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetMinAmount");

                    b.Property<decimal?>("BudgetSpecificAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetSpecificAmount");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompanyName");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CountryCode");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 15, 21, 26, 223, DateTimeKind.Local).AddTicks(9599))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime?>("DesiredEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DesiredEndDate");

                    b.Property<DateTime?>("DesiredStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DesiredStartDate");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<int?>("NumberOfFloors")
                        .HasColumnType("int")
                        .HasColumnName("NumberOfFloors");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNo");

                    b.Property<int>("PreferredCommunicationMethod")
                        .HasColumnType("int")
                        .HasColumnName("PreferredCommunicationMethod");

                    b.Property<int?>("ProjectCategory")
                        .HasColumnType("int")
                        .HasColumnName("ProjectCategory");

                    b.Property<int?>("ProjectDurationDays")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationDays");

                    b.Property<int?>("ProjectDurationHours")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationHours");

                    b.Property<int?>("ProjectDurationMonths")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationMonths");

                    b.Property<string>("ProjectServiceTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ProjectServiceTypeCode");

                    b.Property<int>("ReferralSource")
                        .HasColumnType("int")
                        .HasColumnName("ReferralSource");

                    b.Property<Guid?>("RequestorUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RequestorUserProfileId");

                    b.Property<string>("SiteAddressLine1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SiteAddressLine1");

                    b.Property<string>("SiteAddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SiteAddressLine2");

                    b.Property<string>("SiteCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteCity");

                    b.Property<string>("SiteCountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("SiteCountryCode");

                    b.Property<string>("SiteProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SiteProjectName");

                    b.Property<string>("SiteStateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteStateOrRegion");

                    b.Property<string>("SiteZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SiteZipCode");

                    b.Property<string>("SpecialRequirementsOrFeatures")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("SpecialRequirementsOrFeatures");

                    b.Property<double?>("SquareArea")
                        .HasColumnType("float")
                        .HasColumnName("SquareArea");

                    b.Property<int?>("SquareAreaUoM")
                        .HasColumnType("int")
                        .HasColumnName("SquareAreaUoM");

                    b.Property<string>("StateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StateOrRegion");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("RequestorUserProfileId");

                    b.ToTable("QuoteRequests", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequestAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestAttachmentId")
                        .HasColumnOrder(0);

                    b.Property<string>("AssetCDNUrl")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AssetCDNUrl");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 15, 21, 26, 224, DateTimeKind.Local).AddTicks(4259))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar")
                        .HasColumnName("OriginalFilename");

                    b.Property<Guid>("QuoteRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestId");

                    b.HasKey("Id");

                    b.HasIndex("QuoteRequestId");

                    b.ToTable("QuoteRequestAttachments", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.SiteArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SiteAreaId")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 15, 21, 26, 217, DateTimeKind.Local).AddTicks(9534))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("SiteAreas", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25bdddd3-dfc2-4775-a93f-fe1a98cf9323"),
                            Code = "LCS-01",
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4711),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4712),
                            IsActive = true,
                            Name = "About"
                        },
                        new
                        {
                            Id = new Guid("9e7b39d8-86e2-4925-95ab-0a30e603af8c"),
                            Code = "LCS-02",
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4715),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4715),
                            IsActive = true,
                            Name = "Service"
                        },
                        new
                        {
                            Id = new Guid("01adbac7-4f20-4300-8792-a70c3932e87b"),
                            Code = "LCS-03",
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4725),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4726),
                            IsActive = true,
                            Name = "Teams"
                        },
                        new
                        {
                            Id = new Guid("562bc141-f419-474c-a218-323d351c1b59"),
                            Code = "LCS-04",
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4728),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4728),
                            IsActive = true,
                            Name = "Projects"
                        },
                        new
                        {
                            Id = new Guid("73fd64e6-07c8-43ec-9be0-9f94f2dad724"),
                            Code = "LCS-05",
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4729),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4730),
                            IsActive = true,
                            Name = "Blogs"
                        },
                        new
                        {
                            Id = new Guid("4e7beb33-9575-408d-a4c9-4918cc90a708"),
                            Code = "LCS-06",
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4732),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4732),
                            IsActive = true,
                            Name = "FAQs"
                        },
                        new
                        {
                            Id = new Guid("441f4378-715b-4dc3-9081-1c65960de990"),
                            Code = "LCS-07",
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4734),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4734),
                            IsActive = true,
                            Name = "ClientReviews"
                        },
                        new
                        {
                            Id = new Guid("5a8423fe-705c-4cfa-9eca-4dd719816830"),
                            Code = "LCS-08",
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4736),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4736),
                            IsActive = true,
                            Name = "Contact"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SubscriberId")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 15, 21, 26, 223, DateTimeKind.Local).AddTicks(1654))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.HasKey("Id");

                    b.ToTable("Subscribers", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileModelId")
                        .HasColumnOrder(0);

                    b.Property<string>("BusinessInstitutionName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("BusinessInstitutionName");

                    b.Property<string>("ClientCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ClientCode");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 15, 21, 26, 217, DateTimeKind.Local).AddTicks(1197))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FirstName");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("Gender");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdentityUserId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LastName");

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MobilePhoneNo");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProfileImageUrl");

                    b.Property<string>("Salutation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Salutation");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ThumbnailUrl");

                    b.HasKey("Id");

                    b.ToTable("UserProfileModels", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("298ec5a2-660f-4d29-82c6-8bb69b83c3b6"),
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4577),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4580),
                            FirstName = "James",
                            Gender = 0,
                            IdentityUserId = new Guid("3c4d2914-5bfe-49f5-b81c-94a3e6789d1f"),
                            IsActive = true,
                            LastName = "Mangubat",
                            MobilePhoneNo = "+639672814641",
                            ThumbnailUrl = "https://res.cloudinary.com/dkgz8tnno/image/upload/v1714817540/Picture_of_me_1.bmp_mx2ysp.jpg"
                        },
                        new
                        {
                            Id = new Guid("89458483-cb6f-4db7-af2e-f108d05666f0"),
                            DateCreated = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4617),
                            DateModified = new DateTime(2024, 5, 31, 7, 21, 26, 356, DateTimeKind.Utc).AddTicks(4617),
                            FirstName = "Charles",
                            Gender = 0,
                            IdentityUserId = new Guid("c604f261-fd9d-4881-b640-47dbe5569295"),
                            IsActive = true,
                            LastName = "Reyes",
                            MobilePhoneNo = "+639951225449",
                            ThumbnailUrl = "https://res.cloudinary.com/dkgz8tnno/image/upload/v1714817701/LADON_Team_01_evs4u3.jpg_355_434_-_Google_Chrome_240504181359_ymc3lv.png"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Address", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("Addresses")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogComment", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", "BlogDocument")
                        .WithMany("Comments")
                        .HasForeignKey("BlogDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogDocument");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "AuthorUserProfile")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorUserProfileId");

                    b.Navigation("AuthorUserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogRelatedAssociation", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", "SourceBlogDocument")
                        .WithMany("RelatedPostsFrom")
                        .HasForeignKey("SourceBlogDocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", "TargetBlogDocument")
                        .WithMany("RelatedPostsTo")
                        .HasForeignKey("TargetBlogDocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceBlogDocument");

                    b.Navigation("TargetBlogDocument");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.ClientTestimony", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("ClientTestimonies")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Message", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("Messages")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "RequestorUserProfile")
                        .WithMany("QuoteRequests")
                        .HasForeignKey("RequestorUserProfileId");

                    b.Navigation("RequestorUserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequestAttachment", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", "QuoteRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RelatedPostsFrom");

                    b.Navigation("RelatedPostsTo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Blogs");

                    b.Navigation("ClientTestimonies");

                    b.Navigation("Messages");

                    b.Navigation("QuoteRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
