// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMEAppHouse.Ladon.Infrastructure.Persistence;

#nullable disable

namespace SMEAppHouse.Ladon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240608112416_AddedImportanceMarkerForFAQs")]
    partial class AddedImportanceMarkerForFAQs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5c45204-162a-4057-a2d1-2c8cdcf1c7b2"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("adb82ab0-e728-47a1-918f-0bde869a7fd9"),
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("b306b698-2fbe-4960-b23f-94f17c19728f"),
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = new Guid("fe1e3ada-9017-4f5a-86cc-490e5daaa934"),
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = new Guid("be257fef-fd55-4376-a16c-1deaf8ff5ae9"),
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = new Guid("0d5e48df-23d7-42b2-bc0c-5d3ba4a09cb3"),
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("601b8873-ed96-46e9-ae18-5ae098183d2b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c14da110-b4c2-489f-9804-b5458f9a6105",
                            Email = "jc.mangubat@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JC.MANGUBAT@HOTMAIL.COM",
                            NormalizedUserName = "JC.MANGUBAT@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGHy1OK/bg6gbbBhk2oMnndsC2CpSum3DDvxRP9mwRpO7zogg45Vpv+uc9RxNIiW/Q==",
                            PhoneNumber = "+639672814641",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb300f90-cbac-fa7b-39da-744667f7f0d8_20240608112415375",
                            TwoFactorEnabled = false,
                            UserName = "jc.mangubat@hotmail.com"
                        },
                        new
                        {
                            Id = new Guid("d855ad02-4668-4167-a178-52d5763159cb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b97bb01b-1c4d-45e8-b3ff-8ce46097aa58",
                            Email = "ladonconst@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LADONCONST@GMAIL.COM",
                            NormalizedUserName = "LADONCONST@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDJllJlSE45aXZF7uRxf9IpqsJzoy6gHpcp6FW2GjTFMAogVa9qcayhQnL3cNSRcKA==",
                            PhoneNumber = "+639951225449",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb300f90-cbac-fa7b-39da-744667f7f0d8_20240608112415375",
                            TwoFactorEnabled = false,
                            UserName = "ladonconst@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("601b8873-ed96-46e9-ae18-5ae098183d2b"),
                            RoleId = new Guid("d5c45204-162a-4057-a2d1-2c8cdcf1c7b2")
                        },
                        new
                        {
                            UserId = new Guid("d855ad02-4668-4167-a178-52d5763159cb"),
                            RoleId = new Guid("adb82ab0-e728-47a1-918f-0bde869a7fd9")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("Name")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AddressId")
                        .HasColumnOrder(0);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AddressLine2");

                    b.Property<int>("AddressType")
                        .HasColumnType("int")
                        .HasColumnName("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 361, DateTimeKind.Local).AddTicks(2214))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("Region")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Region");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Addresses", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("da71831c-e385-41b4-8aed-7eb4aae6e2c4"),
                            AddressLine1 = "Lot20 Blk10 Park Villas 1",
                            AddressLine2 = "Ellenita Heights, Catalunan Grande",
                            AddressType = 2,
                            City = "Davao",
                            Country = "Philippines",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9174),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9174),
                            IsActive = true,
                            PostalCode = "8000",
                            Region = "Davao del Sur",
                            UserProfileId = new Guid("1ae96038-5a0b-40ed-a429-21b4912d9716")
                        },
                        new
                        {
                            Id = new Guid("0b50959e-8451-4c33-a529-8727eb444f9d"),
                            AddressLine1 = "",
                            AddressLine2 = "Tierra Nueva Tacunan, Tugbok",
                            AddressType = 2,
                            City = "Davao",
                            Country = "Philippines",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9182),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9182),
                            IsActive = true,
                            PostalCode = "8000",
                            Region = "Davao del Sur",
                            UserProfileId = new Guid("b2e3eb43-2d55-4d34-844b-3a00d44508da")
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogCategoryId")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 371, DateTimeKind.Local).AddTicks(2419))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("BlogCategories", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogCommentId")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("AuthorName");

                    b.Property<Guid?>("BlogPostId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogPostId");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("CommentText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 371, DateTimeKind.Local).AddTicks(6544))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("BlogComments", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82483c3e-a668-4d9c-8cdb-3595186c1592"),
                            AuthorName = "John Doe",
                            BlogPostId = new Guid("a26b6741-e1ad-400d-857e-92b0f5782b56"),
                            CommentText = "This is a fantastic article!",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9536),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9536),
                            Email = "commenter@gmail.com",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogPostId")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthorName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AuthorName");

                    b.Property<Guid?>("AuthorUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuthorUserProfileId");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CanonicalUrl");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 362, DateTimeKind.Local).AddTicks(7720))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<int?>("Hearts")
                        .HasColumnType("int")
                        .HasColumnName("Hearts");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("IsFeatured");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModified");

                    b.Property<int?>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("Likes");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MetaDescription");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MetaKeywords");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PublishedDate");

                    b.Property<string>("Slug")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Slug");

                    b.Property<string>("Tags")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Title");

                    b.Property<int?>("Views")
                        .HasColumnType("int")
                        .HasColumnName("Views");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserProfileId");

                    b.ToTable("BlogPosts", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a26b6741-e1ad-400d-857e-92b0f5782b56"),
                            AuthorUserProfileId = new Guid("1ae96038-5a0b-40ed-a429-21b4912d9716"),
                            Content = "Creating holy sanctuaries with inspired design, fostering spiritual growth and community.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9227),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9228),
                            IsActive = true,
                            PublishedDate = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9386),
                            Slug = "sanctifying-spaces-crafting-sacred-church-architecture",
                            Title = "Sanctifying Spaces: Crafting Sacred Church Architecture"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPostCategory", b =>
                {
                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogPostId", "BlogCategoryId");

                    b.HasIndex("BlogCategoryId");

                    b.ToTable("BlogPostCategory", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogRelatedAssociation", b =>
                {
                    b.Property<Guid>("SourceBlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetBlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SourceBlogPostId", "TargetBlogPostId");

                    b.HasIndex("TargetBlogPostId");

                    b.ToTable("BlogRelatedAssociation", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.ClientTestimony", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClientTestimonyId")
                        .HasColumnOrder(0);

                    b.Property<string>("ClientBusinessName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ClientBusinessName");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ClientName");

                    b.Property<string>("ClientProfession")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ClientProfession");

                    b.Property<string>("ClientThumnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ClientThumnailUrl");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 362, DateTimeKind.Local).AddTicks(3464))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive")
                        .HasColumnOrder(506);

                    b.Property<string>("ProjectImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProjectImageUrl");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Remarks");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ClientTestimonies", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MessageId")
                        .HasColumnOrder(0);

                    b.Property<string>("ContentHtml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentHtml");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 360, DateTimeKind.Local).AddTicks(7562))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MobilePhoneNo");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("SiteMessageSource")
                        .HasColumnType("int")
                        .HasColumnName("SiteMessageSource");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Subject");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Messages", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuestionAnswerId")
                        .HasColumnOrder(0);

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("AnswerText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 374, DateTimeKind.Local).AddTicks(9162))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsImportant")
                        .HasColumnType("bit")
                        .HasColumnName("IsImportant");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Question");

                    b.HasKey("Id");

                    b.ToTable("QuestionAnswers", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70c042db-57dd-4bba-86c5-43759bd4b663"),
                            AnswerText = "Ladon Construction Services offers a wide range of construction services, including residential and commercial building, renovation, remodeling, and custom design-build projects. For more of the services offered, please scroll above to check out the Services we are offerring.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9575),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9575),
                            IsActive = true,
                            IsImportant = true,
                            Question = "What services does Ladon Construction Services offer?"
                        },
                        new
                        {
                            Id = new Guid("90ec4d69-ef71-4119-bb6d-0a89b4652cfd"),
                            AnswerText = "Ladon Construction Services has been proudly serving clients for over 15 years, delivering high-quality construction and renovation projects.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9579),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9579),
                            IsActive = true,
                            IsImportant = true,
                            Question = "How long has Ladon Construction Services been in business?"
                        },
                        new
                        {
                            Id = new Guid("3a210d45-bb2d-415f-a90e-25cb7923576a"),
                            AnswerText = "You can request a quote by filling out the form on our 'Request a Quote' page, or by contacting us directly via email or phone.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9591),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9591),
                            IsActive = true,
                            Question = "How can I get a quote for my project?"
                        },
                        new
                        {
                            Id = new Guid("dbbb2a4d-1876-4fdf-a5d0-6f483307619b"),
                            AnswerText = "We work closely with our clients to establish realistic timelines and ensure that all milestones are met.Our project management team oversees every phase to keep things on track.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9593),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9593),
                            IsActive = true,
                            IsImportant = true,
                            Question = "How do you handle project timelines?"
                        },
                        new
                        {
                            Id = new Guid("e6455220-4214-4beb-abf2-8fff58e21110"),
                            AnswerText = "Yes, we offer comprehensive design-build services, which means we can assist you from the initial design concept through to the final construction.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9595),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9595),
                            IsActive = true,
                            Question = "Can you help with the design phase of my project?"
                        },
                        new
                        {
                            Id = new Guid("64a32be9-1d89-4eeb-8c7f-1498712098f9"),
                            AnswerText = "Important considerations include your budget, desired timeline, the scope of the project, and any specific requirements or preferences you may have.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9596),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9597),
                            IsActive = true,
                            IsImportant = true,
                            Question = "What should I consider before starting a construction project?"
                        },
                        new
                        {
                            Id = new Guid("3512b77e-9dd8-4325-8bc0-385168c1ac26"),
                            AnswerText = "Yes, we provide a warranty for all our construction projects to ensure your satisfaction and peace of mind.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9598),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9598),
                            IsActive = true,
                            IsImportant = true,
                            Question = "Do you provide a warranty for your work?"
                        },
                        new
                        {
                            Id = new Guid("9261277b-56b7-4f34-a7a8-6e7e504f828e"),
                            AnswerText = "Project costs are determined based on the scope of work, materials, labor, and any specific client requirements. We provide detailed estimates to ensure transparency.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9600),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9601),
                            IsActive = true,
                            Question = "How do you determine the cost of a construction project?"
                        },
                        new
                        {
                            Id = new Guid("b362dd0f-8b9b-46aa-9dc2-ef100c353a83"),
                            AnswerText = "Yes, we offer flexible financing options to help make your construction project more affordable.Please contact us for more details.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9608),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9608),
                            IsActive = true,
                            Question = "Do you offer financing options?"
                        },
                        new
                        {
                            Id = new Guid("7f26899b-0278-456d-927d-f81e36a399d6"),
                            AnswerText = "No, our estimates are transparent and all - inclusive.We believe in honesty and integrity in all our dealings.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9610),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9610),
                            IsActive = true,
                            IsImportant = true,
                            Question = "Are there any hidden fees in your estimates?"
                        },
                        new
                        {
                            Id = new Guid("4d74f8fc-b402-432f-af84-05f69844b77a"),
                            AnswerText = "We accept various forms of payment, including bank transfers, credit cards, and financing options. Payment schedules are outlined in our contracts.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9617),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9617),
                            IsActive = true,
                            Question = "How do I pay for my project?"
                        },
                        new
                        {
                            Id = new Guid("06627c2f-2b36-4eab-9a63-945bd8b95406"),
                            AnswerText = "We use high - quality materials and employ skilled craftsmen.Our project managers oversee all work to ensure it meets our stringent quality standards.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9619),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9619),
                            IsActive = true,
                            IsImportant = true,
                            Question = "How do you ensure the quality of your construction work?"
                        },
                        new
                        {
                            Id = new Guid("12dbdef8-0ccd-408b-bfc4-c8bbcf751cf1"),
                            AnswerText = "Safety is a top priority for us.We follow all industry safety standards and regulations, and our team is trained in best safety practices.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9621),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9621),
                            IsActive = true,
                            Question = "What safety measures do you take on construction sites?"
                        },
                        new
                        {
                            Id = new Guid("28539c9e-4c21-43b1-84df-29626662a39c"),
                            AnswerText = "Yes, Ladon Construction Services is fully licensed and insured to operate in the construction industry.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9622),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9623),
                            IsActive = true,
                            IsImportant = true,
                            Question = "Are you licensed and insured?"
                        },
                        new
                        {
                            Id = new Guid("2a40b490-e4c4-4677-878f-ce35d0e3349b"),
                            AnswerText = "We provide regular updates through meetings, emails, and our project management portal, ensuring you are always informed about the progress.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9624),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9625),
                            IsActive = true,
                            Question = "How will I be updated on the progress of my project?"
                        },
                        new
                        {
                            Id = new Guid("69f3d714-3d4c-483a-8e67-15cf84f2fced"),
                            AnswerText = "Changes can be made, but they may affect the timeline and budget. We will work with you to accommodate any changes as smoothly as possible.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9626),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9626),
                            IsActive = true,
                            Question = "What if I need to make changes to the project after it has started?"
                        },
                        new
                        {
                            Id = new Guid("7911a5bb-976d-4c35-88a0-4ef1b00ada01"),
                            AnswerText = "You will be assigned a dedicated project manager who will be your main point of contact throughout the duration of your project.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9628),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9628),
                            IsActive = true,
                            IsImportant = true,
                            Question = "Who will be my point of contact during the project?"
                        },
                        new
                        {
                            Id = new Guid("b874bd15-a61b-4920-9d44-2b2589723511"),
                            AnswerText = "Yes, clients are welcome to visit the construction site. Please coordinate with your project manager to ensure safety and scheduling.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9630),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9630),
                            IsActive = true,
                            Question = "Can I visit the construction site during the project?"
                        },
                        new
                        {
                            Id = new Guid("4431a332-f3c7-4ebf-a639-e3e9a979ee80"),
                            AnswerText = "Upon completion, we conduct a thorough walkthrough with you to ensure everything is to your satisfaction.We also provide a comprehensive handover package, including all necessary documentation.",
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9634),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9634),
                            IsActive = true,
                            Question = "How do you handle project completion and handover?"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestId")
                        .HasColumnOrder(0);

                    b.Property<string>("AdditionalCommentsOrQuestions")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("AdditionalCommentsOrQuestions");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AddressLine2");

                    b.Property<decimal?>("BudgetMaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetMaxAmount");

                    b.Property<decimal?>("BudgetMinAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetMinAmount");

                    b.Property<decimal?>("BudgetSpecificAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetSpecificAmount");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompanyName");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CountryCode");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 373, DateTimeKind.Local).AddTicks(8590))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime?>("DesiredEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DesiredEndDate");

                    b.Property<DateTime?>("DesiredStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DesiredStartDate");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<int?>("NumberOfFloors")
                        .HasColumnType("int")
                        .HasColumnName("NumberOfFloors");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNo");

                    b.Property<int>("PreferredCommunicationMethod")
                        .HasColumnType("int")
                        .HasColumnName("PreferredCommunicationMethod");

                    b.Property<int?>("ProjectCategory")
                        .HasColumnType("int")
                        .HasColumnName("ProjectCategory");

                    b.Property<int?>("ProjectDurationDays")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationDays");

                    b.Property<int?>("ProjectDurationHours")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationHours");

                    b.Property<int?>("ProjectDurationMonths")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationMonths");

                    b.Property<string>("ProjectServiceTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ProjectServiceTypeCode");

                    b.Property<int>("ReferralSource")
                        .HasColumnType("int")
                        .HasColumnName("ReferralSource");

                    b.Property<Guid?>("RequestorUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RequestorUserProfileId");

                    b.Property<string>("SiteAddressLine1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SiteAddressLine1");

                    b.Property<string>("SiteAddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SiteAddressLine2");

                    b.Property<string>("SiteCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteCity");

                    b.Property<string>("SiteCountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("SiteCountryCode");

                    b.Property<string>("SiteProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SiteProjectName");

                    b.Property<string>("SiteStateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteStateOrRegion");

                    b.Property<string>("SiteZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SiteZipCode");

                    b.Property<string>("SpecialRequirementsOrFeatures")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("SpecialRequirementsOrFeatures");

                    b.Property<double?>("SquareArea")
                        .HasColumnType("float")
                        .HasColumnName("SquareArea");

                    b.Property<int?>("SquareAreaUoM")
                        .HasColumnType("int")
                        .HasColumnName("SquareAreaUoM");

                    b.Property<string>("StateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StateOrRegion");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("RequestorUserProfileId");

                    b.ToTable("QuoteRequests", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequestAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestAttachmentId")
                        .HasColumnOrder(0);

                    b.Property<string>("AssetCDNUrl")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AssetCDNUrl");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 374, DateTimeKind.Local).AddTicks(5906))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar")
                        .HasColumnName("OriginalFilename");

                    b.Property<Guid>("QuoteRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestId");

                    b.HasKey("Id");

                    b.HasIndex("QuoteRequestId");

                    b.ToTable("QuoteRequestAttachments", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SubscriberId")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 372, DateTimeKind.Local).AddTicks(3139))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.HasKey("Id");

                    b.ToTable("Subscribers", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileModelId")
                        .HasColumnOrder(0);

                    b.Property<string>("BusinessInstitutionName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("BusinessInstitutionName");

                    b.Property<string>("ClientCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ClientCode");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 19, 24, 15, 360, DateTimeKind.Local).AddTicks(373))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FirstName");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("Gender");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdentityUserId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LastName");

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MobilePhoneNo");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProfileImageUrl");

                    b.Property<string>("Salutation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Salutation");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ThumbnailUrl");

                    b.HasKey("Id");

                    b.ToTable("UserProfileModels", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ae96038-5a0b-40ed-a429-21b4912d9716"),
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9012),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9016),
                            FirstName = "James",
                            Gender = 0,
                            IdentityUserId = new Guid("601b8873-ed96-46e9-ae18-5ae098183d2b"),
                            IsActive = true,
                            LastName = "Mangubat",
                            MobilePhoneNo = "+639672814641",
                            ThumbnailUrl = "https://res.cloudinary.com/dkgz8tnno/image/upload/v1714817540/Picture_of_me_1.bmp_mx2ysp.jpg"
                        },
                        new
                        {
                            Id = new Guid("b2e3eb43-2d55-4d34-844b-3a00d44508da"),
                            DateCreated = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9063),
                            DateModified = new DateTime(2024, 6, 8, 11, 24, 15, 522, DateTimeKind.Utc).AddTicks(9063),
                            FirstName = "Charles",
                            Gender = 0,
                            IdentityUserId = new Guid("d855ad02-4668-4167-a178-52d5763159cb"),
                            IsActive = true,
                            LastName = "Reyes",
                            MobilePhoneNo = "+639951225449",
                            ThumbnailUrl = "https://res.cloudinary.com/dkgz8tnno/image/upload/v1714817701/LADON_Team_01_evs4u3.jpg_355_434_-_Google_Chrome_240504181359_ymc3lv.png"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Address", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("Addresses")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogComment", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "AuthorUserProfile")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorUserProfileId");

                    b.Navigation("AuthorUserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPostCategory", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogCategory", "BlogCategory")
                        .WithMany("BlogPostCategories")
                        .HasForeignKey("BlogCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "BlogPost")
                        .WithMany("BlogPostCategories")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogCategory");

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogRelatedAssociation", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "SourceBlogPost")
                        .WithMany("RelatedPostsFrom")
                        .HasForeignKey("SourceBlogPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "TargetBlogPost")
                        .WithMany("RelatedPostsTo")
                        .HasForeignKey("TargetBlogPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceBlogPost");

                    b.Navigation("TargetBlogPost");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.ClientTestimony", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("ClientTestimonies")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Message", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("Messages")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "RequestorUserProfile")
                        .WithMany("QuoteRequests")
                        .HasForeignKey("RequestorUserProfileId");

                    b.Navigation("RequestorUserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequestAttachment", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", "QuoteRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogCategory", b =>
                {
                    b.Navigation("BlogPostCategories");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", b =>
                {
                    b.Navigation("BlogPostCategories");

                    b.Navigation("Comments");

                    b.Navigation("RelatedPostsFrom");

                    b.Navigation("RelatedPostsTo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Blogs");

                    b.Navigation("ClientTestimonies");

                    b.Navigation("Messages");

                    b.Navigation("QuoteRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
