// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMEAppHouse.Ladon.Infrastructure.Persistence;

#nullable disable

namespace SMEAppHouse.Ladon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240531135857_BlogPostsLogics")]
    partial class BlogPostsLogics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db66a3b5-94a4-4b49-8c8b-9eec68070466"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("4f1ddd8c-7beb-4659-aa90-6347d750d72a"),
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("46d8b1ca-ae74-45e0-9bef-e4415f7d6deb"),
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = new Guid("94203281-ef11-4a57-9731-049eefa2c51b"),
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = new Guid("d6a4eaef-efb4-4f67-987f-92f8801b4e33"),
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = new Guid("690efa09-905d-465c-b1c6-6a3a341f6803"),
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67941a82-0729-4ae0-adcf-cb2efc9db196"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bf64faee-308b-4b1b-8acf-a0736725228f",
                            Email = "jc.mangubat@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JC.MANGUBAT@HOTMAIL.COM",
                            NormalizedUserName = "JC.MANGUBAT@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA+uTZUGEIUtidHj2s+IUTGx567qFbo5703k6sCO9u0IxQgDparvJhjKO2DAVXFQzw==",
                            PhoneNumber = "+639672814641",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8df1d324-28f2-d260-3fd8-73252175f20b_20240531135855930",
                            TwoFactorEnabled = false,
                            UserName = "jc.mangubat@hotmail.com"
                        },
                        new
                        {
                            Id = new Guid("b89f7644-0dee-4258-a18d-6b4c30bdf15d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d519309d-dcf5-4f41-a50c-62c59af70b2a",
                            Email = "ladonconst@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LADONCONST@GMAIL.COM",
                            NormalizedUserName = "LADONCONST@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDSLIjDpYe2bCUfXKFzD9XFE2oajA/Bn8Wa6wqfFUjvDuMK765AU7YM4T/C2EWfGYg==",
                            PhoneNumber = "+639951225449",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8df1d324-28f2-d260-3fd8-73252175f20b_20240531135855930",
                            TwoFactorEnabled = false,
                            UserName = "ladonconst@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("67941a82-0729-4ae0-adcf-cb2efc9db196"),
                            RoleId = new Guid("db66a3b5-94a4-4b49-8c8b-9eec68070466")
                        },
                        new
                        {
                            UserId = new Guid("b89f7644-0dee-4258-a18d-6b4c30bdf15d"),
                            RoleId = new Guid("4f1ddd8c-7beb-4659-aa90-6347d750d72a")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("Name")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AddressId")
                        .HasColumnOrder(0);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AddressLine2");

                    b.Property<int>("AddressType")
                        .HasColumnType("int")
                        .HasColumnName("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 21, 58, 55, 917, DateTimeKind.Local).AddTicks(4455))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("Region")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Region");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Addresses", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e93f964d-9677-43c7-a175-56b41320b80f"),
                            AddressLine1 = "Lot20 Blk10 Park Villas 1",
                            AddressLine2 = "Ellenita Heights, Catalunan Grande",
                            AddressType = 2,
                            City = "Davao",
                            Country = "Philippines",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5301),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5304),
                            IsActive = true,
                            PostalCode = "8000",
                            Region = "Davao del Sur",
                            UserProfileId = new Guid("0ea9434d-ef5b-4e58-8847-ebeb26017ec1")
                        },
                        new
                        {
                            Id = new Guid("0332302e-e837-4d90-bf17-a863e9e13827"),
                            AddressLine1 = "",
                            AddressLine2 = "Tierra Nueva Tacunan, Tugbok",
                            AddressType = 2,
                            City = "Davao",
                            Country = "Philippines",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5335),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5335),
                            IsActive = true,
                            PostalCode = "8000",
                            Region = "Davao del Sur",
                            UserProfileId = new Guid("6e10a069-4a29-453a-9ef4-ddb9c62855ec")
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogCommentId")
                        .HasColumnOrder(0);

                    b.Property<Guid?>("BlogDocumentId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogDocumentId");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("CommentText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 21, 58, 55, 927, DateTimeKind.Local).AddTicks(9496))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("BlogDocumentId");

                    b.ToTable("BlogComments", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d7b8083-0104-4b00-a683-4e14ab678c43"),
                            BlogDocumentId = new Guid("82c5d921-57cc-41e1-89cf-2ec01e636bc9"),
                            CommentText = "This is a fantastic article!",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5860),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5861),
                            Email = "commenter@gmail.com",
                            IsActive = true,
                            Name = "John Doe"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogDocumentId")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthorName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AuthorName");

                    b.Property<Guid?>("AuthorUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuthorUserProfileId");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CanonicalUrl");

                    b.Property<string>("Categories")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Categories");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 21, 58, 55, 919, DateTimeKind.Local).AddTicks(5526))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<int?>("Hearts")
                        .HasColumnType("int")
                        .HasColumnName("Hearts");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("IsFeatured");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModified");

                    b.Property<int?>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("Likes");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MetaDescription");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MetaKeywords");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PublishedDate");

                    b.Property<string>("Slug")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Slug");

                    b.Property<string>("Tags")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Title");

                    b.Property<int?>("Views")
                        .HasColumnType("int")
                        .HasColumnName("Views");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserProfileId");

                    b.ToTable("BlogDocuments", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82c5d921-57cc-41e1-89cf-2ec01e636bc9"),
                            AuthorUserProfileId = new Guid("0ea9434d-ef5b-4e58-8847-ebeb26017ec1"),
                            Content = "Creating holy sanctuaries with inspired design, fostering spiritual growth and community.",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5546),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5546),
                            IsActive = true,
                            PublishedDate = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5550),
                            Title = "Sanctifying Spaces: Crafting Sacred Church Architecture"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogRelatedAssociation", b =>
                {
                    b.Property<Guid>("SourceBlogDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetBlogDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SourceBlogDocumentId", "TargetBlogDocumentId");

                    b.HasIndex("TargetBlogDocumentId");

                    b.ToTable("BlogRelatedAssociation", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.ClientTestimony", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClientTestimonyId")
                        .HasColumnOrder(0);

                    b.Property<string>("ClientBusinessName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ClientBusinessName");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ClientName");

                    b.Property<string>("ClientProfession")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ClientProfession");

                    b.Property<string>("ClientThumnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ClientThumnailUrl");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 21, 58, 55, 918, DateTimeKind.Local).AddTicks(9888))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive")
                        .HasColumnOrder(506);

                    b.Property<string>("ProjectImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProjectImageUrl");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Remarks");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ClientTestimonies", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MessageId")
                        .HasColumnOrder(0);

                    b.Property<string>("ContentHtml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentHtml");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 21, 58, 55, 916, DateTimeKind.Local).AddTicks(6929))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MobilePhoneNo");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("SiteMessageSource")
                        .HasColumnType("int")
                        .HasColumnName("SiteMessageSource");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Subject");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Messages", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestId")
                        .HasColumnOrder(0);

                    b.Property<string>("AdditionalCommentsOrQuestions")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("AdditionalCommentsOrQuestions");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AddressLine2");

                    b.Property<decimal?>("BudgetMaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetMaxAmount");

                    b.Property<decimal?>("BudgetMinAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetMinAmount");

                    b.Property<decimal?>("BudgetSpecificAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetSpecificAmount");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompanyName");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CountryCode");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 21, 58, 55, 929, DateTimeKind.Local).AddTicks(8544))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime?>("DesiredEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DesiredEndDate");

                    b.Property<DateTime?>("DesiredStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DesiredStartDate");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<int?>("NumberOfFloors")
                        .HasColumnType("int")
                        .HasColumnName("NumberOfFloors");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNo");

                    b.Property<int>("PreferredCommunicationMethod")
                        .HasColumnType("int")
                        .HasColumnName("PreferredCommunicationMethod");

                    b.Property<int?>("ProjectCategory")
                        .HasColumnType("int")
                        .HasColumnName("ProjectCategory");

                    b.Property<int?>("ProjectDurationDays")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationDays");

                    b.Property<int?>("ProjectDurationHours")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationHours");

                    b.Property<int?>("ProjectDurationMonths")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationMonths");

                    b.Property<string>("ProjectServiceTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ProjectServiceTypeCode");

                    b.Property<int>("ReferralSource")
                        .HasColumnType("int")
                        .HasColumnName("ReferralSource");

                    b.Property<Guid?>("RequestorUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RequestorUserProfileId");

                    b.Property<string>("SiteAddressLine1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SiteAddressLine1");

                    b.Property<string>("SiteAddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SiteAddressLine2");

                    b.Property<string>("SiteCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteCity");

                    b.Property<string>("SiteCountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("SiteCountryCode");

                    b.Property<string>("SiteProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SiteProjectName");

                    b.Property<string>("SiteStateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteStateOrRegion");

                    b.Property<string>("SiteZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SiteZipCode");

                    b.Property<string>("SpecialRequirementsOrFeatures")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("SpecialRequirementsOrFeatures");

                    b.Property<double?>("SquareArea")
                        .HasColumnType("float")
                        .HasColumnName("SquareArea");

                    b.Property<int?>("SquareAreaUoM")
                        .HasColumnType("int")
                        .HasColumnName("SquareAreaUoM");

                    b.Property<string>("StateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StateOrRegion");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("RequestorUserProfileId");

                    b.ToTable("QuoteRequests", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequestAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestAttachmentId")
                        .HasColumnOrder(0);

                    b.Property<string>("AssetCDNUrl")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AssetCDNUrl");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 21, 58, 55, 930, DateTimeKind.Local).AddTicks(6291))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar")
                        .HasColumnName("OriginalFilename");

                    b.Property<Guid>("QuoteRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestId");

                    b.HasKey("Id");

                    b.HasIndex("QuoteRequestId");

                    b.ToTable("QuoteRequestAttachments", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.SiteArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SiteAreaId")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 21, 58, 55, 917, DateTimeKind.Local).AddTicks(494))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("SiteAreas", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3962d3da-b00b-440f-8be8-a990d67cb3b0"),
                            Code = "LCS-01",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5395),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5396),
                            IsActive = true,
                            Name = "About"
                        },
                        new
                        {
                            Id = new Guid("821bd0be-229c-41a3-af47-fab12363cfd6"),
                            Code = "LCS-02",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5401),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5402),
                            IsActive = true,
                            Name = "Service"
                        },
                        new
                        {
                            Id = new Guid("69c4895d-8171-44f7-8031-b112636a1de4"),
                            Code = "LCS-03",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5404),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5405),
                            IsActive = true,
                            Name = "Teams"
                        },
                        new
                        {
                            Id = new Guid("085d2862-2a7b-4856-9653-9dbb8182cb4a"),
                            Code = "LCS-04",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5408),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5408),
                            IsActive = true,
                            Name = "Projects"
                        },
                        new
                        {
                            Id = new Guid("1d9ddde8-36a1-4566-93ce-1d8e6fbe3d98"),
                            Code = "LCS-05",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5411),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5411),
                            IsActive = true,
                            Name = "Blogs"
                        },
                        new
                        {
                            Id = new Guid("5d28a826-1483-41ed-b48d-e48486334cb1"),
                            Code = "LCS-06",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5415),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5415),
                            IsActive = true,
                            Name = "FAQs"
                        },
                        new
                        {
                            Id = new Guid("da714bf1-ae7a-4cfc-a46e-7c56b5f81f35"),
                            Code = "LCS-07",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5435),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5435),
                            IsActive = true,
                            Name = "ClientReviews"
                        },
                        new
                        {
                            Id = new Guid("4c82ea05-d718-432a-8799-1490dd479111"),
                            Code = "LCS-08",
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5444),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(5444),
                            IsActive = true,
                            Name = "Contact"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SubscriberId")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 21, 58, 55, 928, DateTimeKind.Local).AddTicks(3750))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.HasKey("Id");

                    b.ToTable("Subscribers", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileModelId")
                        .HasColumnOrder(0);

                    b.Property<string>("BusinessInstitutionName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("BusinessInstitutionName");

                    b.Property<string>("ClientCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ClientCode");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 5, 31, 21, 58, 55, 915, DateTimeKind.Local).AddTicks(917))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FirstName");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("Gender");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdentityUserId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LastName");

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MobilePhoneNo");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProfileImageUrl");

                    b.Property<string>("Salutation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Salutation");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ThumbnailUrl");

                    b.HasKey("Id");

                    b.ToTable("UserProfileModels", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ea9434d-ef5b-4e58-8847-ebeb26017ec1"),
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(4796),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(4799),
                            FirstName = "James",
                            Gender = 0,
                            IdentityUserId = new Guid("67941a82-0729-4ae0-adcf-cb2efc9db196"),
                            IsActive = true,
                            LastName = "Mangubat",
                            MobilePhoneNo = "+639672814641",
                            ThumbnailUrl = "https://res.cloudinary.com/dkgz8tnno/image/upload/v1714817540/Picture_of_me_1.bmp_mx2ysp.jpg"
                        },
                        new
                        {
                            Id = new Guid("6e10a069-4a29-453a-9ef4-ddb9c62855ec"),
                            DateCreated = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(4850),
                            DateModified = new DateTime(2024, 5, 31, 13, 58, 56, 189, DateTimeKind.Utc).AddTicks(4851),
                            FirstName = "Charles",
                            Gender = 0,
                            IdentityUserId = new Guid("b89f7644-0dee-4258-a18d-6b4c30bdf15d"),
                            IsActive = true,
                            LastName = "Reyes",
                            MobilePhoneNo = "+639951225449",
                            ThumbnailUrl = "https://res.cloudinary.com/dkgz8tnno/image/upload/v1714817701/LADON_Team_01_evs4u3.jpg_355_434_-_Google_Chrome_240504181359_ymc3lv.png"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Address", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("Addresses")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogComment", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", "BlogDocument")
                        .WithMany("Comments")
                        .HasForeignKey("BlogDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogDocument");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "AuthorUserProfile")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorUserProfileId");

                    b.Navigation("AuthorUserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogRelatedAssociation", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", "SourceBlogDocument")
                        .WithMany("RelatedPostsFrom")
                        .HasForeignKey("SourceBlogDocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", "TargetBlogDocument")
                        .WithMany("RelatedPostsTo")
                        .HasForeignKey("TargetBlogDocumentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceBlogDocument");

                    b.Navigation("TargetBlogDocument");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.ClientTestimony", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("ClientTestimonies")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Message", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("Messages")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "RequestorUserProfile")
                        .WithMany("QuoteRequests")
                        .HasForeignKey("RequestorUserProfileId");

                    b.Navigation("RequestorUserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequestAttachment", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", "QuoteRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogDocument", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("RelatedPostsFrom");

                    b.Navigation("RelatedPostsTo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Blogs");

                    b.Navigation("ClientTestimonies");

                    b.Navigation("Messages");

                    b.Navigation("QuoteRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
