// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMEAppHouse.Ladon.Infrastructure.Persistence;

#nullable disable

namespace SMEAppHouse.Ladon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240608104406_FAQsAndSeed")]
    partial class FAQsAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc21e1b3-dcc3-4bf6-acef-15d04417f916"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("f143e2f2-7ecc-4e59-9607-42e17ef73420"),
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("63bb0685-c393-42b3-82e5-e0b84ad88b9f"),
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = new Guid("93e57c25-4050-4c7d-bb84-b84467c189a4"),
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = new Guid("deafbbd0-f283-49bf-9d1c-d94b2c9a3a0c"),
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = new Guid("fb3d762c-ed6c-43bf-a0a4-6113dce4ebee"),
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e75b23c7-08c1-40c5-a847-5b4f99d201d2"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f50c3db0-5ad1-4aaf-b836-0d3a6025fc97",
                            Email = "jc.mangubat@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JC.MANGUBAT@HOTMAIL.COM",
                            NormalizedUserName = "JC.MANGUBAT@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDYWPRQRipFf29ZjXJ6D/u+sjbes3PWw+KKeeBsvDmNsF8FHdN/a78epm6l5G5Mm0A==",
                            PhoneNumber = "+639672814641",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e3c83a30-7b0f-26f3-7b57-fbd9f8791c34_20240608104404764",
                            TwoFactorEnabled = false,
                            UserName = "jc.mangubat@hotmail.com"
                        },
                        new
                        {
                            Id = new Guid("3dc6f035-97ff-4253-9eff-21a92da5b0cf"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "91693ab4-a16d-42ff-b261-29352f0dc1f6",
                            Email = "ladonconst@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LADONCONST@GMAIL.COM",
                            NormalizedUserName = "LADONCONST@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO9ROyeLwPGW5sUkjkJmHFeAyOGX25YUdH43OfZUbs57dnV8vWqk8DFfgw7nMBmOtQ==",
                            PhoneNumber = "+639951225449",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e3c83a30-7b0f-26f3-7b57-fbd9f8791c34_20240608104404764",
                            TwoFactorEnabled = false,
                            UserName = "ladonconst@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e75b23c7-08c1-40c5-a847-5b4f99d201d2"),
                            RoleId = new Guid("cc21e1b3-dcc3-4bf6-acef-15d04417f916")
                        },
                        new
                        {
                            UserId = new Guid("3dc6f035-97ff-4253-9eff-21a92da5b0cf"),
                            RoleId = new Guid("f143e2f2-7ecc-4e59-9607-42e17ef73420")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("Name")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AddressId")
                        .HasColumnOrder(0);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AddressLine2");

                    b.Property<int>("AddressType")
                        .HasColumnType("int")
                        .HasColumnName("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 751, DateTimeKind.Local).AddTicks(4998))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("Region")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Region");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Addresses", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c58f36fb-ae6b-4a2e-a381-b29c702cf4c7"),
                            AddressLine1 = "Lot20 Blk10 Park Villas 1",
                            AddressLine2 = "Ellenita Heights, Catalunan Grande",
                            AddressType = 2,
                            City = "Davao",
                            Country = "Philippines",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(9),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(10),
                            IsActive = true,
                            PostalCode = "8000",
                            Region = "Davao del Sur",
                            UserProfileId = new Guid("6a4a7886-7639-49dd-bab4-30644d51c961")
                        },
                        new
                        {
                            Id = new Guid("8c198c93-8433-4861-a558-8cc76a7d5e82"),
                            AddressLine1 = "",
                            AddressLine2 = "Tierra Nueva Tacunan, Tugbok",
                            AddressType = 2,
                            City = "Davao",
                            Country = "Philippines",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(15),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(16),
                            IsActive = true,
                            PostalCode = "8000",
                            Region = "Davao del Sur",
                            UserProfileId = new Guid("bb0ac16e-77bb-448b-9a65-733a0af44a5a")
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogCategoryId")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 760, DateTimeKind.Local).AddTicks(9040))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("BlogCategories", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogCommentId")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("AuthorName");

                    b.Property<Guid?>("BlogPostId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogPostId");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("CommentText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 761, DateTimeKind.Local).AddTicks(2961))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("BlogComments", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73c6c1ae-bdfd-45cf-8c3e-c95accdb4cff"),
                            AuthorName = "John Doe",
                            BlogPostId = new Guid("1bee9053-99f3-4b39-a23a-1e03d579e1db"),
                            CommentText = "This is a fantastic article!",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(319),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(319),
                            Email = "commenter@gmail.com",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogPostId")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthorName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AuthorName");

                    b.Property<Guid?>("AuthorUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuthorUserProfileId");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CanonicalUrl");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 752, DateTimeKind.Local).AddTicks(8746))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<int?>("Hearts")
                        .HasColumnType("int")
                        .HasColumnName("Hearts");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("IsFeatured");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModified");

                    b.Property<int?>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("Likes");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MetaDescription");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MetaKeywords");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PublishedDate");

                    b.Property<string>("Slug")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Slug");

                    b.Property<string>("Tags")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Title");

                    b.Property<int?>("Views")
                        .HasColumnType("int")
                        .HasColumnName("Views");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserProfileId");

                    b.ToTable("BlogPosts", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1bee9053-99f3-4b39-a23a-1e03d579e1db"),
                            AuthorUserProfileId = new Guid("6a4a7886-7639-49dd-bab4-30644d51c961"),
                            Content = "Creating holy sanctuaries with inspired design, fostering spiritual growth and community.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(279),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(279),
                            IsActive = true,
                            PublishedDate = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(282),
                            Slug = "sanctifying-spaces-crafting-sacred-church-architecture",
                            Title = "Sanctifying Spaces: Crafting Sacred Church Architecture"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPostCategory", b =>
                {
                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogPostId", "BlogCategoryId");

                    b.HasIndex("BlogCategoryId");

                    b.ToTable("BlogPostCategory", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogRelatedAssociation", b =>
                {
                    b.Property<Guid>("SourceBlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetBlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SourceBlogPostId", "TargetBlogPostId");

                    b.HasIndex("TargetBlogPostId");

                    b.ToTable("BlogRelatedAssociation", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.ClientTestimony", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClientTestimonyId")
                        .HasColumnOrder(0);

                    b.Property<string>("ClientBusinessName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ClientBusinessName");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ClientName");

                    b.Property<string>("ClientProfession")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ClientProfession");

                    b.Property<string>("ClientThumnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ClientThumnailUrl");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 752, DateTimeKind.Local).AddTicks(4200))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive")
                        .HasColumnOrder(506);

                    b.Property<string>("ProjectImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProjectImageUrl");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Remarks");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ClientTestimonies", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MessageId")
                        .HasColumnOrder(0);

                    b.Property<string>("ContentHtml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentHtml");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 750, DateTimeKind.Local).AddTicks(6409))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MobilePhoneNo");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("SiteMessageSource")
                        .HasColumnType("int")
                        .HasColumnName("SiteMessageSource");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Subject");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Messages", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuestionAnswerId")
                        .HasColumnOrder(0);

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("AnswerText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 764, DateTimeKind.Local).AddTicks(2199))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Question");

                    b.HasKey("Id");

                    b.ToTable("QuestionAnswers", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("209ae0f8-7e2a-4218-a25d-3fc7f261595a"),
                            AnswerText = "Ladon Construction Services offers a wide range of construction services, including residential and commercial building, renovation, remodeling, and custom design-build projects. For more of the services offered, please scroll above to check out the Services we are offerring.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(376),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(374),
                            IsActive = true,
                            Question = "What services does Ladon Construction Services offer?"
                        },
                        new
                        {
                            Id = new Guid("0dc6e761-0b8c-4d6c-92fb-57790cddf978"),
                            AnswerText = "Ladon Construction Services has been proudly serving clients for over 15 years, delivering high-quality construction and renovation projects.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(388),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(387),
                            IsActive = true,
                            Question = "How long has Ladon Construction Services been in business?"
                        },
                        new
                        {
                            Id = new Guid("bd3d41e7-8c4f-4130-8642-7f86f11064de"),
                            AnswerText = "You can request a quote by filling out the form on our 'Request a Quote' page, or by contacting us directly via email or phone.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(391),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(390),
                            IsActive = true,
                            Question = "How can I get a quote for my project?"
                        },
                        new
                        {
                            Id = new Guid("7f37d6f8-c50d-4771-83e0-12a89dc29a37"),
                            AnswerText = "We work closely with our clients to establish realistic timelines and ensure that all milestones are met.Our project management team oversees every phase to keep things on track.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(393),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(392),
                            IsActive = true,
                            Question = "How do you handle project timelines?"
                        },
                        new
                        {
                            Id = new Guid("81ab4bdc-51c0-4ea6-a827-154580c6ab9a"),
                            AnswerText = "Yes, we offer comprehensive design-build services, which means we can assist you from the initial design concept through to the final construction.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(396),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(395),
                            IsActive = true,
                            Question = "Can you help with the design phase of my project?"
                        },
                        new
                        {
                            Id = new Guid("8c70b9b1-2617-4c00-8a36-705738cfe031"),
                            AnswerText = "Important considerations include your budget, desired timeline, the scope of the project, and any specific requirements or preferences you may have.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(398),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(397),
                            IsActive = true,
                            Question = "What should I consider before starting a construction project?"
                        },
                        new
                        {
                            Id = new Guid("d94c3a75-edff-4e73-9c6d-10642be9b6b7"),
                            AnswerText = "Yes, we provide a warranty for all our construction projects to ensure your satisfaction and peace of mind.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(401),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(399),
                            IsActive = true,
                            Question = "Do you provide a warranty for your work?"
                        },
                        new
                        {
                            Id = new Guid("c028573b-c15f-40c9-aecb-04490ca67165"),
                            AnswerText = "Project costs are determined based on the scope of work, materials, labor, and any specific client requirements. We provide detailed estimates to ensure transparency.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(407),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(403),
                            IsActive = true,
                            Question = "How do you determine the cost of a construction project?"
                        },
                        new
                        {
                            Id = new Guid("e87b7542-dee1-479d-82ea-ccea472660d2"),
                            AnswerText = "Yes, we offer flexible financing options to help make your construction project more affordable.Please contact us for more details.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(410),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(408),
                            IsActive = true,
                            Question = "Do you offer financing options?"
                        },
                        new
                        {
                            Id = new Guid("31290918-2d85-4305-9665-5fbae3578e42"),
                            AnswerText = "No, our estimates are transparent and all - inclusive.We believe in honesty and integrity in all our dealings.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(412),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(411),
                            IsActive = true,
                            Question = "Are there any hidden fees in your estimates?"
                        },
                        new
                        {
                            Id = new Guid("49a4d341-f23f-44a5-8ac3-d4a915d5a136"),
                            AnswerText = "We accept various forms of payment, including bank transfers, credit cards, and financing options. Payment schedules are outlined in our contracts.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(414),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(413),
                            IsActive = true,
                            Question = "How do I pay for my project?"
                        },
                        new
                        {
                            Id = new Guid("b57b085b-0e2a-4b75-8c9c-9c723826f993"),
                            AnswerText = "We use high - quality materials and employ skilled craftsmen.Our project managers oversee all work to ensure it meets our stringent quality standards.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(417),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(416),
                            IsActive = true,
                            Question = "How do you ensure the quality of your construction work?"
                        },
                        new
                        {
                            Id = new Guid("4e5f7cfe-9d1c-442b-a3e6-87ace5d817c1"),
                            AnswerText = "Safety is a top priority for us.We follow all industry safety standards and regulations, and our team is trained in best safety practices.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(420),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(419),
                            IsActive = true,
                            Question = "What safety measures do you take on construction sites?"
                        },
                        new
                        {
                            Id = new Guid("87b619be-8485-4605-ba80-20792ba8b9cd"),
                            AnswerText = "Yes, Ladon Construction Services is fully licensed and insured to operate in the construction industry.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(429),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(422),
                            IsActive = true,
                            Question = "Are you licensed and insured?"
                        },
                        new
                        {
                            Id = new Guid("601150e1-974b-4e21-99ac-38dfea3a2e71"),
                            AnswerText = "We provide regular updates through meetings, emails, and our project management portal, ensuring you are always informed about the progress.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(434),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(430),
                            IsActive = true,
                            Question = "How will I be updated on the progress of my project?"
                        },
                        new
                        {
                            Id = new Guid("e03b4449-8eb8-4dd5-b495-930a39277aa5"),
                            AnswerText = "Changes can be made, but they may affect the timeline and budget. We will work with you to accommodate any changes as smoothly as possible.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(440),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(435),
                            IsActive = true,
                            Question = "What if I need to make changes to the project after it has started?"
                        },
                        new
                        {
                            Id = new Guid("c7331b53-f2ea-418e-abd3-7bb1af44d5b1"),
                            AnswerText = "You will be assigned a dedicated project manager who will be your main point of contact throughout the duration of your project.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(443),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(441),
                            IsActive = true,
                            Question = "Who will be my point of contact during the project?"
                        },
                        new
                        {
                            Id = new Guid("0b8de8e4-2a17-4891-9716-6dc90fb5a172"),
                            AnswerText = "Yes, clients are welcome to visit the construction site. Please coordinate with your project manager to ensure safety and scheduling.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(445),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(444),
                            IsActive = true,
                            Question = "Can I visit the construction site during the project?"
                        },
                        new
                        {
                            Id = new Guid("9fd3e894-5012-4eb3-8130-22fe2685679e"),
                            AnswerText = "Upon completion, we conduct a thorough walkthrough with you to ensure everything is to your satisfaction.We also provide a comprehensive handover package, including all necessary documentation.",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(447),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(446),
                            IsActive = true,
                            Question = "How do you handle project completion and handover?"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestId")
                        .HasColumnOrder(0);

                    b.Property<string>("AdditionalCommentsOrQuestions")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("AdditionalCommentsOrQuestions");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AddressLine2");

                    b.Property<decimal?>("BudgetMaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetMaxAmount");

                    b.Property<decimal?>("BudgetMinAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetMinAmount");

                    b.Property<decimal?>("BudgetSpecificAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetSpecificAmount");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompanyName");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CountryCode");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 763, DateTimeKind.Local).AddTicks(1254))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime?>("DesiredEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DesiredEndDate");

                    b.Property<DateTime?>("DesiredStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DesiredStartDate");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<int?>("NumberOfFloors")
                        .HasColumnType("int")
                        .HasColumnName("NumberOfFloors");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNo");

                    b.Property<int>("PreferredCommunicationMethod")
                        .HasColumnType("int")
                        .HasColumnName("PreferredCommunicationMethod");

                    b.Property<int?>("ProjectCategory")
                        .HasColumnType("int")
                        .HasColumnName("ProjectCategory");

                    b.Property<int?>("ProjectDurationDays")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationDays");

                    b.Property<int?>("ProjectDurationHours")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationHours");

                    b.Property<int?>("ProjectDurationMonths")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationMonths");

                    b.Property<string>("ProjectServiceTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ProjectServiceTypeCode");

                    b.Property<int>("ReferralSource")
                        .HasColumnType("int")
                        .HasColumnName("ReferralSource");

                    b.Property<Guid?>("RequestorUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RequestorUserProfileId");

                    b.Property<string>("SiteAddressLine1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SiteAddressLine1");

                    b.Property<string>("SiteAddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SiteAddressLine2");

                    b.Property<string>("SiteCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteCity");

                    b.Property<string>("SiteCountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("SiteCountryCode");

                    b.Property<string>("SiteProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SiteProjectName");

                    b.Property<string>("SiteStateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteStateOrRegion");

                    b.Property<string>("SiteZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SiteZipCode");

                    b.Property<string>("SpecialRequirementsOrFeatures")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("SpecialRequirementsOrFeatures");

                    b.Property<double?>("SquareArea")
                        .HasColumnType("float")
                        .HasColumnName("SquareArea");

                    b.Property<int?>("SquareAreaUoM")
                        .HasColumnType("int")
                        .HasColumnName("SquareAreaUoM");

                    b.Property<string>("StateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StateOrRegion");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("RequestorUserProfileId");

                    b.ToTable("QuoteRequests", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequestAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestAttachmentId")
                        .HasColumnOrder(0);

                    b.Property<string>("AssetCDNUrl")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AssetCDNUrl");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 763, DateTimeKind.Local).AddTicks(8454))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar")
                        .HasColumnName("OriginalFilename");

                    b.Property<Guid>("QuoteRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestId");

                    b.HasKey("Id");

                    b.HasIndex("QuoteRequestId");

                    b.ToTable("QuoteRequestAttachments", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.SiteArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SiteAreaId")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 751, DateTimeKind.Local).AddTicks(628))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("SiteAreas", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6dee099d-5ce1-4083-a8e8-e69d658c03b2"),
                            Code = "LCS-01",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(196),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(197),
                            IsActive = true,
                            Name = "About"
                        },
                        new
                        {
                            Id = new Guid("3331675f-2ded-4494-b661-fe6f8998377a"),
                            Code = "LCS-02",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(201),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(201),
                            IsActive = true,
                            Name = "Service"
                        },
                        new
                        {
                            Id = new Guid("62d6ff5d-b9cb-44d8-89a6-548b8e5921ac"),
                            Code = "LCS-03",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(212),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(212),
                            IsActive = true,
                            Name = "Teams"
                        },
                        new
                        {
                            Id = new Guid("46d74252-fd9b-4688-89fd-9512bbc35d69"),
                            Code = "LCS-04",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(215),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(215),
                            IsActive = true,
                            Name = "Projects"
                        },
                        new
                        {
                            Id = new Guid("eb7f736d-75c9-49de-963b-0de13178ceab"),
                            Code = "LCS-05",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(217),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(217),
                            IsActive = true,
                            Name = "Blogs"
                        },
                        new
                        {
                            Id = new Guid("f20b4ff2-8393-4b4d-91f5-61783c208f54"),
                            Code = "LCS-06",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(219),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(219),
                            IsActive = true,
                            Name = "FAQs"
                        },
                        new
                        {
                            Id = new Guid("4c32b708-1653-404d-8a1a-ea20a2f6458c"),
                            Code = "LCS-07",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(221),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(221),
                            IsActive = true,
                            Name = "ClientReviews"
                        },
                        new
                        {
                            Id = new Guid("1248104f-89e2-4382-b030-4f6833aa4dc3"),
                            Code = "LCS-08",
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(223),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 903, DateTimeKind.Utc).AddTicks(223),
                            IsActive = true,
                            Name = "Contact"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SubscriberId")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 761, DateTimeKind.Local).AddTicks(8625))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.HasKey("Id");

                    b.ToTable("Subscribers", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileModelId")
                        .HasColumnOrder(0);

                    b.Property<string>("BusinessInstitutionName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("BusinessInstitutionName");

                    b.Property<string>("ClientCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ClientCode");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 8, 18, 44, 4, 749, DateTimeKind.Local).AddTicks(4999))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FirstName");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("Gender");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdentityUserId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LastName");

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MobilePhoneNo");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProfileImageUrl");

                    b.Property<string>("Salutation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Salutation");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ThumbnailUrl");

                    b.HasKey("Id");

                    b.ToTable("UserProfileModels", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a4a7886-7639-49dd-bab4-30644d51c961"),
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 902, DateTimeKind.Utc).AddTicks(9859),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 902, DateTimeKind.Utc).AddTicks(9864),
                            FirstName = "James",
                            Gender = 0,
                            IdentityUserId = new Guid("e75b23c7-08c1-40c5-a847-5b4f99d201d2"),
                            IsActive = true,
                            LastName = "Mangubat",
                            MobilePhoneNo = "+639672814641",
                            ThumbnailUrl = "https://res.cloudinary.com/dkgz8tnno/image/upload/v1714817540/Picture_of_me_1.bmp_mx2ysp.jpg"
                        },
                        new
                        {
                            Id = new Guid("bb0ac16e-77bb-448b-9a65-733a0af44a5a"),
                            DateCreated = new DateTime(2024, 6, 8, 10, 44, 4, 902, DateTimeKind.Utc).AddTicks(9907),
                            DateModified = new DateTime(2024, 6, 8, 10, 44, 4, 902, DateTimeKind.Utc).AddTicks(9908),
                            FirstName = "Charles",
                            Gender = 0,
                            IdentityUserId = new Guid("3dc6f035-97ff-4253-9eff-21a92da5b0cf"),
                            IsActive = true,
                            LastName = "Reyes",
                            MobilePhoneNo = "+639951225449",
                            ThumbnailUrl = "https://res.cloudinary.com/dkgz8tnno/image/upload/v1714817701/LADON_Team_01_evs4u3.jpg_355_434_-_Google_Chrome_240504181359_ymc3lv.png"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Address", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("Addresses")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogComment", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "AuthorUserProfile")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorUserProfileId");

                    b.Navigation("AuthorUserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPostCategory", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogCategory", "BlogCategory")
                        .WithMany("BlogPostCategories")
                        .HasForeignKey("BlogCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "BlogPost")
                        .WithMany("BlogPostCategories")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogCategory");

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogRelatedAssociation", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "SourceBlogPost")
                        .WithMany("RelatedPostsFrom")
                        .HasForeignKey("SourceBlogPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "TargetBlogPost")
                        .WithMany("RelatedPostsTo")
                        .HasForeignKey("TargetBlogPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceBlogPost");

                    b.Navigation("TargetBlogPost");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.ClientTestimony", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("ClientTestimonies")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Message", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("Messages")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "RequestorUserProfile")
                        .WithMany("QuoteRequests")
                        .HasForeignKey("RequestorUserProfileId");

                    b.Navigation("RequestorUserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequestAttachment", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", "QuoteRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogCategory", b =>
                {
                    b.Navigation("BlogPostCategories");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", b =>
                {
                    b.Navigation("BlogPostCategories");

                    b.Navigation("Comments");

                    b.Navigation("RelatedPostsFrom");

                    b.Navigation("RelatedPostsTo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Blogs");

                    b.Navigation("ClientTestimonies");

                    b.Navigation("Messages");

                    b.Navigation("QuoteRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
