// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SMEAppHouse.Ladon.Infrastructure.Persistence;

#nullable disable

namespace SMEAppHouse.Ladon.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240601034613_AddedBlogCategory")]
    partial class AddedBlogCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e168070e-6345-4630-b520-62bdc66f5081"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("92439679-dcc6-482d-8d35-b0818ce21256"),
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = new Guid("8df3ddcf-fae0-4f97-894c-e0ab5d153537"),
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = new Guid("33c82a8d-9f3f-4eb0-87bc-141918ca913f"),
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = new Guid("f2bbcabc-0779-49f2-9413-fd13574d5f32"),
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = new Guid("4bb4532b-1884-4359-9f5e-50c7e682bdc2"),
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d30188eb-8213-4ba8-99c8-a450c84220b6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f2547ef-5068-4eca-8ef3-6570d715941c",
                            Email = "jc.mangubat@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JC.MANGUBAT@HOTMAIL.COM",
                            NormalizedUserName = "JC.MANGUBAT@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENOQAtbUWGx7Y7PxVPQZjAOGNuJeYnGlakZ9ZkyXPg/TtViSS4c0bcORcGF2C4W6ww==",
                            PhoneNumber = "+639672814641",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ad519418-ad1d-d67b-613b-b1f8b0272630_20240601034611676",
                            TwoFactorEnabled = false,
                            UserName = "jc.mangubat@hotmail.com"
                        },
                        new
                        {
                            Id = new Guid("756e42b2-d955-4b35-8988-8c1717fe64aa"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c43cbe48-de60-4f09-ad35-89fb3902061b",
                            Email = "ladonconst@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LADONCONST@GMAIL.COM",
                            NormalizedUserName = "LADONCONST@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPbYS2LifQTcEs+QT57Orv4Qr6ghvPu5tOa5QDbfMNn/1SrSDCAB+ieRTl1IlLkS8g==",
                            PhoneNumber = "+639951225449",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ad519418-ad1d-d67b-613b-b1f8b0272630_20240601034611676",
                            TwoFactorEnabled = false,
                            UserName = "ladonconst@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "dbo");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d30188eb-8213-4ba8-99c8-a450c84220b6"),
                            RoleId = new Guid("e168070e-6345-4630-b520-62bdc66f5081")
                        },
                        new
                        {
                            UserId = new Guid("756e42b2-d955-4b35-8988-8c1717fe64aa"),
                            RoleId = new Guid("92439679-dcc6-482d-8d35-b0818ce21256")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("Name")
                        .HasMaxLength(112)
                        .HasColumnType("nvarchar(112)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AddressId")
                        .HasColumnOrder(0);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("AddressLine2");

                    b.Property<int>("AddressType")
                        .HasColumnType("int")
                        .HasColumnName("AddressType");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("City");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Country");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 649, DateTimeKind.Local).AddTicks(6399))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("Region")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Region");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Addresses", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bf1b1b6-6807-4ea8-ba50-c3c302cf3d96"),
                            AddressLine1 = "Lot20 Blk10 Park Villas 1",
                            AddressLine2 = "Ellenita Heights, Catalunan Grande",
                            AddressType = 2,
                            City = "Davao",
                            Country = "Philippines",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5247),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5248),
                            IsActive = true,
                            PostalCode = "8000",
                            Region = "Davao del Sur",
                            UserProfileId = new Guid("b8aa91ce-eadd-417f-a55d-b8e413e699ad")
                        },
                        new
                        {
                            Id = new Guid("23dbe370-15a1-4d60-b054-d17607e5b29a"),
                            AddressLine1 = "",
                            AddressLine2 = "Tierra Nueva Tacunan, Tugbok",
                            AddressType = 2,
                            City = "Davao",
                            Country = "Philippines",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5256),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5256),
                            IsActive = true,
                            PostalCode = "8000",
                            Region = "Davao del Sur",
                            UserProfileId = new Guid("738a4d8d-36dc-4660-b2d0-044d53295503")
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogCategoryId")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 662, DateTimeKind.Local).AddTicks(9637))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("BlogCategories", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogCommentId")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("AuthorName");

                    b.Property<Guid?>("BlogPostId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogPostId");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("CommentText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 663, DateTimeKind.Local).AddTicks(6487))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Email");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("BlogComments", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25a00e41-1c96-4c27-bc1c-5fe347211a4a"),
                            AuthorName = "John Doe",
                            BlogPostId = new Guid("21b76fe6-937a-4c00-bf03-77065ab15143"),
                            CommentText = "This is a fantastic article!",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5392),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5392),
                            Email = "commenter@gmail.com",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BlogPostId")
                        .HasColumnOrder(0);

                    b.Property<string>("AuthorName")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AuthorName");

                    b.Property<Guid?>("AuthorUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AuthorUserProfileId");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("CanonicalUrl");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 652, DateTimeKind.Local).AddTicks(67))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<int?>("Hearts")
                        .HasColumnType("int")
                        .HasColumnName("Hearts");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("bit")
                        .HasColumnName("IsFeatured");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModified");

                    b.Property<int?>("Likes")
                        .HasColumnType("int")
                        .HasColumnName("Likes");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MetaDescription");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("MetaKeywords");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PublishedDate");

                    b.Property<string>("Slug")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Slug");

                    b.Property<string>("Tags")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("Tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Title");

                    b.Property<int?>("Views")
                        .HasColumnType("int")
                        .HasColumnName("Views");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserProfileId");

                    b.ToTable("BlogPosts", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21b76fe6-937a-4c00-bf03-77065ab15143"),
                            AuthorUserProfileId = new Guid("b8aa91ce-eadd-417f-a55d-b8e413e699ad"),
                            Content = "Creating holy sanctuaries with inspired design, fostering spiritual growth and community.",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5362),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5362),
                            IsActive = true,
                            PublishedDate = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5364),
                            Slug = "sanctifying-spaces-crafting-sacred-church-architecture",
                            Title = "Sanctifying Spaces: Crafting Sacred Church Architecture"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPostCategory", b =>
                {
                    b.Property<Guid>("BlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BlogCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BlogPostId", "BlogCategoryId");

                    b.HasIndex("BlogCategoryId");

                    b.ToTable("BlogPostCategory", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogRelatedAssociation", b =>
                {
                    b.Property<Guid>("SourceBlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetBlogPostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SourceBlogPostId", "TargetBlogPostId");

                    b.HasIndex("TargetBlogPostId");

                    b.ToTable("BlogRelatedAssociation", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.ClientTestimony", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClientTestimonyId")
                        .HasColumnOrder(0);

                    b.Property<string>("ClientBusinessName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ClientBusinessName");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("ClientName");

                    b.Property<string>("ClientProfession")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("ClientProfession");

                    b.Property<string>("ClientThumnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ClientThumnailUrl");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 651, DateTimeKind.Local).AddTicks(4161))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("IsActive")
                        .HasColumnOrder(506);

                    b.Property<string>("ProjectImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProjectImageUrl");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Remarks");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("ClientTestimonies", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MessageId")
                        .HasColumnOrder(0);

                    b.Property<string>("ContentHtml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentHtml");

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContentText");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 648, DateTimeKind.Local).AddTicks(4823))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MobilePhoneNo");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("SiteMessageSource")
                        .HasColumnType("int")
                        .HasColumnName("SiteMessageSource");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Subject");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileId");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Messages", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestId")
                        .HasColumnOrder(0);

                    b.Property<string>("AdditionalCommentsOrQuestions")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("AdditionalCommentsOrQuestions");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("AddressLine2");

                    b.Property<decimal?>("BudgetMaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetMaxAmount");

                    b.Property<decimal?>("BudgetMinAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetMinAmount");

                    b.Property<decimal?>("BudgetSpecificAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BudgetSpecificAmount");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("City");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompanyName");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("CountryCode");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 666, DateTimeKind.Local).AddTicks(3185))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<DateTime?>("DesiredEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DesiredEndDate");

                    b.Property<DateTime?>("DesiredStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DesiredStartDate");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LastName");

                    b.Property<int?>("NumberOfFloors")
                        .HasColumnType("int")
                        .HasColumnName("NumberOfFloors");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PhoneNo");

                    b.Property<int>("PreferredCommunicationMethod")
                        .HasColumnType("int")
                        .HasColumnName("PreferredCommunicationMethod");

                    b.Property<int?>("ProjectCategory")
                        .HasColumnType("int")
                        .HasColumnName("ProjectCategory");

                    b.Property<int?>("ProjectDurationDays")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationDays");

                    b.Property<int?>("ProjectDurationHours")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationHours");

                    b.Property<int?>("ProjectDurationMonths")
                        .HasColumnType("int")
                        .HasColumnName("ProjectDurationMonths");

                    b.Property<string>("ProjectServiceTypeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ProjectServiceTypeCode");

                    b.Property<int>("ReferralSource")
                        .HasColumnType("int")
                        .HasColumnName("ReferralSource");

                    b.Property<Guid?>("RequestorUserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RequestorUserProfileId");

                    b.Property<string>("SiteAddressLine1")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SiteAddressLine1");

                    b.Property<string>("SiteAddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("SiteAddressLine2");

                    b.Property<string>("SiteCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteCity");

                    b.Property<string>("SiteCountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("SiteCountryCode");

                    b.Property<string>("SiteProjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("SiteProjectName");

                    b.Property<string>("SiteStateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SiteStateOrRegion");

                    b.Property<string>("SiteZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SiteZipCode");

                    b.Property<string>("SpecialRequirementsOrFeatures")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar(2400)")
                        .HasColumnName("SpecialRequirementsOrFeatures");

                    b.Property<double?>("SquareArea")
                        .HasColumnType("float")
                        .HasColumnName("SquareArea");

                    b.Property<int?>("SquareAreaUoM")
                        .HasColumnType("int")
                        .HasColumnName("SquareAreaUoM");

                    b.Property<string>("StateOrRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("StateOrRegion");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("RequestorUserProfileId");

                    b.ToTable("QuoteRequests", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequestAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestAttachmentId")
                        .HasColumnOrder(0);

                    b.Property<string>("AssetCDNUrl")
                        .HasMaxLength(2400)
                        .HasColumnType("nvarchar")
                        .HasColumnName("AssetCDNUrl");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 669, DateTimeKind.Local).AddTicks(7084))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar")
                        .HasColumnName("OriginalFilename");

                    b.Property<Guid>("QuoteRequestId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("QuoteRequestId");

                    b.HasKey("Id");

                    b.HasIndex("QuoteRequestId");

                    b.ToTable("QuoteRequestAttachments", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.SiteArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SiteAreaId")
                        .HasColumnOrder(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 649, DateTimeKind.Local).AddTicks(1160))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("SiteAreas", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("786822a3-6753-4bb7-a034-49d603cac4f1"),
                            Code = "LCS-01",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5282),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5282),
                            IsActive = true,
                            Name = "About"
                        },
                        new
                        {
                            Id = new Guid("2fbefbfe-5e42-4770-8506-94af3cf33fdf"),
                            Code = "LCS-02",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5285),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5285),
                            IsActive = true,
                            Name = "Service"
                        },
                        new
                        {
                            Id = new Guid("ffe57815-1afe-47df-af78-7b053f046d2d"),
                            Code = "LCS-03",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5301),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5301),
                            IsActive = true,
                            Name = "Teams"
                        },
                        new
                        {
                            Id = new Guid("1a4a61dd-b7ff-434d-9fc8-cad1e81628f7"),
                            Code = "LCS-04",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5303),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5303),
                            IsActive = true,
                            Name = "Projects"
                        },
                        new
                        {
                            Id = new Guid("09008ba3-0647-46ff-bf29-425da15a2ef7"),
                            Code = "LCS-05",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5305),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5305),
                            IsActive = true,
                            Name = "Blogs"
                        },
                        new
                        {
                            Id = new Guid("15e470c7-7d7a-40d9-ab00-db0a9a7336d8"),
                            Code = "LCS-06",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5307),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5307),
                            IsActive = true,
                            Name = "FAQs"
                        },
                        new
                        {
                            Id = new Guid("cc8a74a7-320b-4049-9c02-ea39d0967da5"),
                            Code = "LCS-07",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5308),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5309),
                            IsActive = true,
                            Name = "ClientReviews"
                        },
                        new
                        {
                            Id = new Guid("91078d6a-7e92-4d08-9c5d-ba72cf0b9774"),
                            Code = "LCS-08",
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5311),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5311),
                            IsActive = true,
                            Name = "Contact"
                        });
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SubscriberId")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 664, DateTimeKind.Local).AddTicks(1272))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("EmailAddress");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.HasKey("Id");

                    b.ToTable("Subscribers", "dbo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserProfileModelId")
                        .HasColumnOrder(0);

                    b.Property<string>("BusinessInstitutionName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("BusinessInstitutionName");

                    b.Property<string>("ClientCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ClientCode");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("DateTime2")
                        .HasDefaultValue(new DateTime(2024, 6, 1, 11, 46, 11, 646, DateTimeKind.Local).AddTicks(7981))
                        .HasColumnName("_dateCreated")
                        .HasColumnOrder(501);

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2")
                        .HasColumnName("_dateModified")
                        .HasColumnOrder(508);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FirstName");

                    b.Property<int>("Gender")
                        .HasColumnType("int")
                        .HasColumnName("Gender");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdentityUserId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnOrder(506);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LastName");

                    b.Property<string>("MobilePhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MobilePhoneNo");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ProfileImageUrl");

                    b.Property<string>("Salutation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Salutation");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ThumbnailUrl");

                    b.HasKey("Id");

                    b.ToTable("UserProfileModels", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8aa91ce-eadd-417f-a55d-b8e413e699ad"),
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5143),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5146),
                            FirstName = "James",
                            Gender = 0,
                            IdentityUserId = new Guid("d30188eb-8213-4ba8-99c8-a450c84220b6"),
                            IsActive = true,
                            LastName = "Mangubat",
                            MobilePhoneNo = "+639672814641",
                            ThumbnailUrl = "https://res.cloudinary.com/dkgz8tnno/image/upload/v1714817540/Picture_of_me_1.bmp_mx2ysp.jpg"
                        },
                        new
                        {
                            Id = new Guid("738a4d8d-36dc-4660-b2d0-044d53295503"),
                            DateCreated = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5181),
                            DateModified = new DateTime(2024, 6, 1, 3, 46, 11, 832, DateTimeKind.Utc).AddTicks(5181),
                            FirstName = "Charles",
                            Gender = 0,
                            IdentityUserId = new Guid("756e42b2-d955-4b35-8988-8c1717fe64aa"),
                            IsActive = true,
                            LastName = "Reyes",
                            MobilePhoneNo = "+639951225449",
                            ThumbnailUrl = "https://res.cloudinary.com/dkgz8tnno/image/upload/v1714817701/LADON_Team_01_evs4u3.jpg_355_434_-_Google_Chrome_240504181359_ymc3lv.png"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Address", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("Addresses")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogComment", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "BlogPost")
                        .WithMany("Comments")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "AuthorUserProfile")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorUserProfileId");

                    b.Navigation("AuthorUserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPostCategory", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogCategory", "BlogCategory")
                        .WithMany("BlogPostCategories")
                        .HasForeignKey("BlogCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "BlogPost")
                        .WithMany("BlogPostCategories")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogCategory");

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogRelatedAssociation", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "SourceBlogPost")
                        .WithMany("RelatedPostsFrom")
                        .HasForeignKey("SourceBlogPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", "TargetBlogPost")
                        .WithMany("RelatedPostsTo")
                        .HasForeignKey("TargetBlogPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceBlogPost");

                    b.Navigation("TargetBlogPost");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.ClientTestimony", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("ClientTestimonies")
                        .HasForeignKey("UserProfileId");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.Message", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "UserProfile")
                        .WithMany("Messages")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", "RequestorUserProfile")
                        .WithMany("QuoteRequests")
                        .HasForeignKey("RequestorUserProfileId");

                    b.Navigation("RequestorUserProfile");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequestAttachment", b =>
                {
                    b.HasOne("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", "QuoteRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("QuoteRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteRequest");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogCategory", b =>
                {
                    b.Navigation("BlogPostCategories");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.BlogPost", b =>
                {
                    b.Navigation("BlogPostCategories");

                    b.Navigation("Comments");

                    b.Navigation("RelatedPostsFrom");

                    b.Navigation("RelatedPostsTo");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.QuoteRequest", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("SMEAppHouse.Ladon.Domain.Entities.EFModels.UserProfileModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Blogs");

                    b.Navigation("ClientTestimonies");

                    b.Navigation("Messages");

                    b.Navigation("QuoteRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
